// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"symops/pkg/models/shared"
)

type GetEventRequest struct {
	// ID of the event to retrieve
	EventID string `pathParam:"style=simple,explode=false,name=event_id"`
}

type GetEventResponse struct {
	ContentType string
	// OK
	Event       *shared.Event
	StatusCode  int
	RawResponse *http.Response
}
