// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// EventLocation - Location of the event
type EventLocation struct {
	// Street address of the location
	Address *string `json:"address,omitempty"`
	// City of the location
	City *string `json:"city,omitempty"`
	// Country of the location
	Country *string `json:"country,omitempty"`
	// State or province of the location
	State *string `json:"state,omitempty"`
}

// Event - OK
type Event struct {
	// Date and time of the event
	Date *time.Time `json:"date,omitempty"`
	// Unique identifier for the event
	ID *string `json:"id,omitempty"`
	// Location of the event
	Location *EventLocation `json:"location,omitempty"`
	// Name of the event
	Name *string `json:"name,omitempty"`
}
